config/routes.rb
JCBookApp::Application.routes.draw do

  scope "/(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: "books#index"
    get 'books/about'
    get 'authors/author'
    resources :books, except: :show
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books

  def self.find_books(id)
    author = where(id: id).take
    if author
      author.books
    else
      []
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, presence: true
  validates :author, presence: true
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  layout "author"

  def author
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :get_page
  before_action :get_a_book, only: [:edit, :update, :destroy]
  before_action :get_books, only: [:index, :edit]

  def index
    @book = Book.new(released_date: Time.now)
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html {
          flash[:notice] = t('messages.success.create')
          redirect_to books_path
        }
        format.js
      else
        format.html { render action: 'index' }
        format.js { render 'message' }
      end
    end
  end

  def edit
    render action: 'index'
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html {
          flash[:notice] = t('messages.success.update')
          redirect_to books_path
        }
        format.js { render 'update', locals: { book: @book } }
      else
        format.html { render action: 'index' }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html {
        redirect_to books_path, notice: t('messages.success.delete')
      }
      format.js { render 'delete', locals: { book: @book } }
    end
  end

  def about
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def get_page
      session[:page] ||= 1
      session[:page] = params[:page].to_i if params[:page]
    end
    def get_a_book
      @book = Book.find(params[:id])
    end
    def get_books_on_page(page=1)
      @books = Book.paginate(page: page, per_page: 10)
    end
    def get_books
      @books = get_books_on_page(session[:page])
      if session[:page] > 1 && @books.empty?
        session[:page] -= 1
        @books = get_books_on_page(session[:page])
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :released_date, :author_id,
        :rating, :available)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/author.html.erb
<div class="header-container">
  <header class="wrapper clearfix">
    <h1 class="title"><%= "#{controller_name}##{action_name}" %></h1>
    <nav class="leaf-menu">
      <ul>
        <li><%= link_to t("menu.book"), books_path %>
          <div id="orange"></div></li>
        <li><%= link_to t("menu.author"), authors_author_path %>
          <div id="blue"></div></li>
        <li><%= link_to t("menu.about"), books_about_path %>
          <div id="purple"></div></li>
      </ul>
    </nav>
  </header>
</div>
<div class="main-container">
  <div class="main wrapper clearfix">
    <article>
      <header>
        <h2>Lorem Ipsum คืออะไร</h2>
        <p>Posted on <time datetime="2009-09-04T16:31:24+02:00">September 4th 2009</time> by <a href="#">Writer</a> - <a href="#comments">6 comments</a></p>
      </header>
      <p>Lorem Ipsum คือ เนื้อหาจำลองแบบเรียบๆ ที่ใช้กันในธุรกิจงานพิมพ์หรืองานเรียงพิมพ์ มันได้กลายมาเป็นเนื้อหาจำลองมาตรฐานของธุรกิจดังกล่าวมาตั้งแต่ศตวรรษที่ 16 เมื่อเครื่องพิมพ์โนเนมเครื่องหนึ่งนำรางตัวพิมพ์มาสลับสับตำแหน่งตัวอักษรเพื่อทำหนังสือตัวอย่าง Lorem Ipsum อยู่ยงคงกระพันมาไม่ใช่แค่เพียงห้าศตวรรษ แต่อยู่มาจนถึงยุคที่พลิกโฉมเข้าสู่งานเรียงพิมพ์ด้วยวิธีทางอิเล็กทรอนิกส์ และยังคงสภาพเดิมไว้อย่างไม่มีการเปลี่ยนแปลง มันได้รับความนิยมมากขึ้นในยุค ค.ศ. 1960 เมื่อแผ่น Letraset วางจำหน่ายโดยมีข้อความบนนั้นเป็น Lorem Ipsum และล่าสุดกว่านั้น คือเมื่อซอฟท์แวร์การทำสื่อสิ่งพิมพ์ (Desktop Publishing) อย่าง Aldus PageMaker ได้รวมเอา Lorem Ipsum เวอร์ชั่นต่างๆ เข้าไว้ในซอฟท์แวร์ด้วย</p>
    </article>
    <aside>
      <h2>ทำไมจึงต้องนำมาใช้</h2>
      <p>มีหลักฐานที่เป็นข้อเท็จจริงยืนยันมานานแล้ว ว่าเนื้อหาที่อ่านรู้เรื่องนั้นจะไปกวนสมาธิของคนอ่านให้เขวไปจากส่วนที้เป็น Layout เรานำ Lorem Ipsum มาใช้เพราะความที่มันมีการกระจายของตัวอักษรธรรมดาๆ แบบพอประมาณ ซึ่งเอามาใช้แทนการเขียนว่า ‘ตรงนี้เป็นเนื้อหา, ตรงนี้เป็นเนื้อหา' ได้ และยังทำให้มองดูเหมือนกับภาษาอังกฤษที่อ่านได้ปกติ ปัจจุบันมีแพ็กเกจของซอฟท์แวร์การทำสื่อสิ่งพิมพ์ และซอฟท์แวร์การสร้างเว็บเพจ (Web Page Editor) หลายตัวที่ใช้ Lorem Ipsum เป็นแบบจำลองเนื้อหาที่เป็นค่าตั้งต้น และเวลาที่เสิร์ชด้วยคำว่า 'lorem ipsum' ผลการเสิร์ชที่ได้ก็จะไม่พบบรรดาเว็บไซต์ที่ยังคงอยู่ในช่วงเริ่มสร้างด้วย โดยหลายปีที่ผ่านมาก็มีการคิดค้นเวอร์ชั่นต่างๆ ของ Lorem Ipsum ขึ้นมาใช้ บ้างก็เป็นความบังเอิญ บ้างก็เป็นความตั้งใจ (เช่น การแอบแทรกมุกตลก)</p>
    </aside>

    <article>
      <header>
        <h2>มันมีที่มาอย่างไร</h2>
        <p>Posted on <time datetime="2009-09-04T16:31:24+02:00">September 4th 2009</time> by <a href="#">Writer</a> - <a href="#comments">6 comments</a></p>
      </header>
      <p>ตรงกันข้ามกับความเชื่อที่นิยมกัน Lorem Ipsum ไม่ได้เป็นเพียงแค่ชุดตัวอักษรที่สุ่มขึ้นมามั่วๆ แต่หากมีที่มาจากวรรณกรรมละตินคลาสสิกชิ้นหนึ่งในยุค 45 ปีก่อนคริสตศักราช ทำให้มันมีอายุถึงกว่า 2000 ปีเลยทีเดียว ริชาร์ด แมคคลินท็อค ศาสตราจารย์ชาวละติน จากวิทยาลัยแฮมพ์เด็น-ซิดนีย์ ในรัฐเวอร์จิเนียร์ นำคำภาษาละตินคำว่า consectetur ซึ่งหาคำแปลไม่ได้จาก Lorem Ipsum ตอนหนึ่งมาค้นเพิ่มเติม โดยตรวจเทียบกับแหล่งอ้างอิงต่างๆ ในวรรณกรรมคลาสสิก และค้นพบแหล่งข้อมูลที่ไร้ข้อกังขาว่า Lorem Ipsum นั้นมาจากตอนที่ 1.10.32 และ 1.10.33 ของเรื่อง "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) ของ ซิเซโร ที่แต่งไว้เมื่อ 45 ปีก่อนคริสตศักราช หนังสือเล่มนี้เป็นเรื่องราวที่ว่าด้วยทฤษฎีแห่งจริยศาสตร์ ซึ่งเป็นที่นิยมมากในยุคเรเนสซองส์ บรรทัดแรกของ Lorem Ipsum "Lorem ipsum dolor sit amet.." ก็มาจากบรรทัดหนึ่งในตอนที่ 1.10.32 นั่นเอง</p>
    </article>
  </div>
</div>
<div class="footer-container">
  <footer class="wrapper">
    <h3>Copyright &copy;2013</h3>
  </footer>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.js"></script>
<script>window.jQuery || document.write('<script src="/assets/jquery-1.10.1.js"><\/script>')</script> <script>window.jQuery || document.write('<script src="/assets/jquery-1.10.1.js"><\/script>')</script>

app/views/books/_data_row.html.erb
<tr id='<%= "book_#{book.id}" %>'>
  <td class="wider"><%= book.title %></td>
  <td class="wide"><%= book.author.name if book.author %></td>
  <td class="tight"><%= l book.released_date, format: :short if book.released_date %></td>
  <td class="tight">
    <div class="rateit" data-rateit-value="<%= book.rating %>" data-rateit-ispreset="true" data-rateit-readonly="true"></div></td>
  <td <%= "class=avail" if book.available %>></td>
  <td><%= link_to image_tag("/assets/icons/action_save.gif"), edit_book_path(book) %>
  <%= link_to image_tag("/assets/icons/action_stop.gif"), book, class: 'delete', method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/books/_footer.html.erb
<div class="footer-container">
  <footer class="wrapper">
    <h3>&copy;418342</h3>
  </footer>
</div>

app/views/books/_form.html.erb
<div class="<%= action_name %>" id="entry_form">
  <%= form_for(@book, remote: @remote) do |f| %>
    <table>
      <tr>
        <th><%= Book.human_attribute_name(:title) %></th>
        <td><%= f.text_field :title, size: 30 %></td>
        <th><%= Book.human_attribute_name(:author) %></th>
        <td><%= f.collection_select :author_id, Author.all,
          :id, :name, { prompt: true, length: 25 },
          { style: "width: 150px;" } %></td></tr>
      <tr>
        <th><%= Book.human_attribute_name(:released) %></th>
        <td><%= f.date_field :released_date %></td>
        <th><%= Book.human_attribute_name(:rating) %></th>
        <td><%= f.range_field :rating, in: 0..5, step: 1,
          id: "book#{@book.id}" %>
          <div class="rateit" data-rateit-backingfld="#book<%= @book.id %>"></div></td>
        <th><%= Book.human_attribute_name(:available) %></th>
        <td><%= f.check_box :available %></td></tr>
    </table>
    <%= f.button class: "button_#{action_name}" %>
    <% if action_name == "edit" %>
      <%= link_to t("button.cancel"), books_path, { method: :get, "data-remote" => :true, class: "button_#{action_name}" } %>
    <% else %>
      <%= button_tag t("button.clear"), type: :reset, class: "button_#{action_name}" %>
    <% end %>
  <% end %>
</div>

app/views/books/_headmenu.html.erb
<div class="header-container">
  <header class="wrapper clearfix">
    <h1 class="title"><%= t :app_title %></h1>
    <nav>
      <ul>
        <li><%= link_to t("menu.book"), books_path,
          class: action_name=='index' ? "selected":"none" %>
        <li><%= link_to t("menu.author"), authors_author_path,
          class: action_name=='author' ? "selected":"none" %>
        <li><%= link_to t("menu.about"), books_about_path,
          class: action_name=='about' ? "selected":"none" %>
      </ul>
    </nav>
  </header>
</div>

app/views/books/_message.html.erb
<% if false && @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= error_messages_for @book %>
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

app/views/books/_rateit.html.erb
<%= coffee_script_tag do %>
  $(document).bind 'page:change', ->
    $('.rateit').rateit()
<% end %>

app/views/books/_show_row.js.coffee.erb
$('#item_holder').append('<%= escape_javascript(render "row_data",
  book: @book).html_safe %>')
$('#item_holder').show()

app/views/books/about.html.erb
<h1>About</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/books/index.html.erb
<div id="message"></div>
<%= render 'message' %>

<% if @books && !@books.empty? %>
  <table class="display" id="new_row">
    <tr>
      <th class="wider"><%= Book.human_attribute_name(:title) %></th>
      <th class="wide"><%= Book.human_attribute_name(:author) %></th>
      <th class="tight"><%= Book.human_attribute_name(:released) %></th>
      <th class="tight"><%= Book.human_attribute_name(:rating) %></th>
      <th class="tighter"><%= Book.human_attribute_name(:available) %></th>
      <th class="tighter"><%= Book.human_attribute_name(:actions) %></th>
    </tr>
    <% for book in @books do %>
      <%= render 'data_row', book: book %>
    <% end %>
  </table>
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @books %>
    </div>
    <%= will_paginate @books, container: false %>
  </div>
  <br>
<% end %>

<%= render 'form' %>

<%= render 'rateit' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t :app_title %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'books/headmenu' %>
    <div class="main wrapper clearfix">
      <%= yield %>
    </div>
    <%= render 'books/footer' %>
  </body>
</html>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Application</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>